import { createFileRoute } from "@tanstack/react-router";
import { FileText, Download } from "lucide-react";
import ReportScheduler from "@/components/dashboard/ReportScheduler";
import ComplianceAudit from "@/components/dashboard/ComplianceAudit";

export const Route = createFileRoute("/dashboard/reports")({
  component: Reports,
});

const reports = [
  { name: "Cycle Audit: October 2023", date: "Nov 1, 2023", size: "2.4 MB" },
  { name: "Quarterly Grid Summary: Q3", date: "Oct 5, 2023", size: "4.1 MB" },
  { name: "Node Audit: September", date: "Oct 2, 2023", size: "1.8 MB" },
  { name: "Node SLA Analytics", date: "Sep 15, 2023", size: "3.2 MB" },
];

function Reports() {
  const handleDownload = (filename: string) => {
    const content = `Mock report data for ${filename}\nGenerated by Powerinova System\nDate: ${new Date().toISOString()}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename.replace(/\s+/g, '_').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ReportScheduler />
        <ComplianceAudit />
      </div>
      <div className="bg-white border border-pi-border rounded-2xl p-5">
        <h3 className="text-teal font-bold text-base">Audit Repository</h3>
        <ul className="mt-4 divide-y divide-pi-border">
          {reports.map((r) => (
            <li key={r.name} className="py-3 flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-cream flex items-center justify-center text-teal">
                <FileText className="w-5 h-5" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-teal truncate">{r.name}</p>
                <p className="text-xs text-muted-sage">{r.date} • {r.size}</p>
              </div>
              <button 
                onClick={() => handleDownload(r.name)}
                className="inline-flex items-center gap-1.5 bg-brand text-white text-xs font-semibold px-3 py-1.5 rounded-lg hover:bg-brand/90 transition-colors"
              >
                <Download className="w-3.5 h-3.5" /> Export
              </button>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}